version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: portfolio_tracker
    volumes:
      - pgdata:/var/lib/postgresql/data

  init-db:
    build:
      context: .
      dockerfile: Dockerfile-init-db
    depends_on:
      - postgres
    restart: "no"

volumes:
  pgdata:
